version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/www/data
      - ./nginx.conf:/etc/nginx/nginx.conf
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "2121:21"
    environment:
      - USERS=admin|admin|/home/admin
