version: "3.3"
services:
  app:
    image: "script"
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: cron -f
    depends_on:
      - nginx
      - ftp
      - adminer
      - db
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/www/data
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: archivage_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  ftp:
    image: delfer/alpine-ftp-server
    restart: always
    ports:
      - "2121:21"
    volumes:
      - ./storage:/home/admin
    environment:
      - USERS=admin|admin|/home/admin
volumes:
  database:
