version: "3.3"
services:
  app:
    image: "script"
    ports: 
    - "5000:1234" 
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: cron -f
    depends_on:
      - nginx
      - ftp
      - db



  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/www/data
      - ./nginx.conf:/etc/nginx/nginx.conf
  documentation:
    image: nginx
    ports:
     - "8081:80"
    volumes:
      - ./doc/html/app:/usr/share/nginx/www
      - ./nginx_doc.conf:/etc/nginx/nginx.conf


  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  smtp:
    image: namshi/smtp
    ports:
      - "2525:25"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  ftp:
    image: delfer/alpine-ftp-server
    restart: always
    ports:
      - "2121:21"
    volumes:
      - ./storage:/home/${FTP_USER}
    environment:
      - USERS=${FTP_USER}|${FTP_PASSWORD}|/home/${FTP_USER}
volumes:
  database:
